### ISSUE TITLE
Success True atau False untuk setiap response termasuk yang GET

### ISSUE THREAD

**Issue by wkwksama** [PinguinJantan/openPackTrack-backend#29]
ini untuk response get item isinya langsung datanya. minta dikasih success true/false nya buat nangani error. kayak yang di POST item.

ndak cuma item, GET yang lain juga bakale butuh

**Comment by arnaz06** [comment]
@wkwksama Itu kelewatan ji, heheh

**Comment by dikyarga** [comment]
Sebenarnya bisa diambil dari statusCode respon nya : https://httpstatuses.com/

tapi ngak apa sih kalo mau dari data nya.
